sudo: required
services:
  - docker

before_install:
  - docker build -t hsimao/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hsimao/react-test npm test

after_success:
  - docker build -t hsimao/multi-client ./client
  - docker build -t hsimao/multi-nginx ./nginx
  - docker build -t hsimao/multi-server ./server
  - docker build -t hsimao/multi-worker ./worker

  # Login docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push hsimao/multi-client
  - docker push hsimao/multi-nginx
  - docker push hsimao/multi-server
  - docker push hsimao/multi-worker
